#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    com.main.writeRoom: DEBUG

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      maxFileSize: 200MB
      maxRequestSize: 300MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
sql:
  init:
    mode: never

chatgpt:
  key: ${GPT_SECRET}

cloud:
  aws:
    s3:
      bucket: writeroom-dev
      path:
        room: rooms
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  expiration_time: 86400000
  secret: ${JWT_SECRET}


oauth:
  kakao:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
    client-id: 911519431154557d9c40bec40ec8884c