#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    com.main.writeRoom: DEBUG

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB  # 최대 파일 사이즈
      max-request-size: 200MB  # 최대 요청 사이즈
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: writeroom.umc@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
sql:
  init:
    mode: never

chatgpt:
  key: ${GPT_SECRET}

cloud:
  aws:
    s3:
      bucket: writeroom-dev
      path:
        room: writeroom
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  expiration_time: 86400000
  secret: ${JWT_SECRET}


#kakao:
#  auth:
#    token:
#      url: http://kauth.kakao.com/oauth/token
#    user:
#      url: http://kapi.kakao.com/v2/user/me
#  client:
#    id: 911519431154557d9c40bec40ec8884c
#  redirect:
#    uri: http://localhost:3000/oauth


oauth:
  kakao:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
    client-id: 911519431154557d9c40bec40ec8884c